services: docker
# sudo: false

language: python
python:
  - '3.6'
install:
  - 'pip install -r docker/requirements.txt'

env:
  - REPO=gazebo TAG=gazebo4
  - REPO=gazebo TAG=gazebo5
  - REPO=gazebo TAG=gazebo6
  - REPO=gazebo TAG=gazebo7
  - REPO=gazebo TAG=gazebo8
  - REPO=ros TAG=indigo
  - REPO=ros TAG=jade
  - REPO=ros TAG=kinetic
  - REPO=ros TAG=lunar
  - REPO=ros2 TAG=ubuntu

script: ./.travis/travis.py
