services: docker
# sudo: false

language: python
python:
  - '3.6'
install:
  - 'pip install -r docker/requirements.txt'

env:
  - REPO=gazebo TAG=gazebo4
  - REPO=gazebo TAG=gazebo5
  - REPO=gazebo TAG=gazebo6
  - REPO=gazebo TAG=gazebo7
  - REPO=gazebo TAG=gazebo8
  - REPO=ros TAG=indigo     OS_NAME=ubuntu OS_CODE_NAME=trusty
  - REPO=ros TAG=jade       OS_NAME=ubuntu OS_CODE_NAME=trusty
  - REPO=ros TAG=kinetic    OS_NAME=ubuntu OS_CODE_NAME=xenial
  - REPO=ros TAG=kinetic    OS_NAME=debian OS_CODE_NAME=jessie
  - REPO=ros TAG=lunar      OS_NAME=ubuntu OS_CODE_NAME=xenial
  - REPO=ros TAG=lunar      OS_NAME=debian OS_CODE_NAME=stretch
  - REPO=ros2 TAG=r2b3      OS_NAME=ubuntu OS_CODE_NAME=xenial

script: ./.travis/travis.py
